default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/postgresql  # ソケットファイルのパスを指定

development:
  <<: *default
  database: myapp_development
  username: your_username  # PostgreSQLのユーザー名を指定
  password: your_password  # 必要に応じてパスワードを設定

test:
  <<: *default
  database: myapp_test
  username: your_username
  password: your_password

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
